# Generated by Django 5.0.1 on 2024-01-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0037_alter_pers_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='poste',
            field=models.CharField(choices=[('Chauffeur', 'chauffeur'), ('Vendeur', 'vendeur'), ('Ouvrier', 'Ouvrier')], max_length=200, null=True),
        ),
    ]
