# Generated by Django 5.0.1 on 2024-01-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0031_alter_spend_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('usine', 'usine'), ('Citroen Jumper', 'CITROEN JUMPER'), ('autres', 'autres'), ('Ford', 'FORD'), ('Toyota', 'Toyota')], max_length=200, null=True),
        ),
    ]
