# Generated by Django 5.0.1 on 2024-01-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0032_alter_spend_actif'),
        ('vente', '0004_alter_prix_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vente.voitures'),
        ),
    ]
