# Generated by Django 5.0.1 on 2024-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0033_alter_spend_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='actif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
