# Generated by Django 5.0.1 on 2024-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0034_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='type_depense',
            field=models.CharField(blank=True, choices=[('charge ordinaire', 'charge ordinaire'), ('charge familliale', 'charge familliale')], max_length=200, null=True),
        ),
    ]
