# Generated by Django 5.0.1 on 2024-04-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0035_alter_spend_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='type_depense',
            field=models.CharField(blank=True, choices=[('charge familliale', 'charge familliale'), ('charge ordinaire', 'charge ordinaire')], max_length=200, null=True),
        ),
    ]
