# Generated by Django 5.0.1 on 2024-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiale', models.IntegerField(null=True)),
                ('nombre_roulaux', models.IntegerField(null=True)),
                ('nombre_emballage', models.IntegerField(null=True)),
                ('poids', models.FloatField(null=True)),
                ('produit', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True, unique=True)),
                ('sortie', models.IntegerField(blank=True, null=True)),
                ('usine', models.IntegerField(blank=True, null=True)),
                ('rentabilité', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
