# Generated by Django 5.0.1 on 2024-01-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prix',
            fields=[
                ('prix', models.FloatField(default=5000, primary_key=True, serialize=False)),
            ],
        ),
    ]
