# Generated by Django 5.0.1 on 2024-01-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0002_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prix',
            name='prix',
            field=models.FloatField(default='5000', primary_key=True, serialize=False),
        ),
    ]
