# Generated by Django 5.0.1 on 2024-04-27 14:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0004_alter_prix_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prix',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sell',
            name='Somme_gnf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='prime',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
    ]
