# Generated by Django 5.0.4 on 2024-05-01 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vente", "0005_alter_prix_prix_alter_sell_somme_gnf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voitures",
            name="prime",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=10
            ),
        ),
    ]
